version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

volumes:
  db: {}
